In [1]:
import pandas as pd
import requests
from io import StringIO

### Problem-1:

You are given a SQL file link: https://drive.google.com/file/d/1WFt7B84LTHhMueoKmz8W-PRo7xXqmZf3/view?usp=share_link. Read the data by using the file and store it in a excel file. In this data, there are 3 tables named "invoices", "order_leads" and "sales_sql". So create 3 sheets to your excel file.

In [3]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB 81.9 kB/s eta 0:02:25
     ---------------------------------------- 0.0/11.9 MB 81.9 kB/s eta 0:02:25
     --------------------------------------- 0.0/11.9 MB 100.4 kB/s eta 0:01:58
     --------------------------------------- 0.0/11.9 MB 122.9 kB/s eta 0:01:37
     --------------------------------------- 0.1/11.9 MB 163.6 kB/s eta 0:01:13
     --------------------------------------- 0.1/11.9 MB 245.8 kB/s eta 0:00:48
      -------------------------------------- 0.2/11.9 MB 509.6 kB/s eta 0:00:23
     - ------------------------------------- 0.3/11.9 MB 633.4 kB/s eta 0:00:19
     - ------------------------------------- 0.5/11.9 MB 861.1 kB/s eta 0:00:14
     -- ------------------------------------- 0.7/11.9 MB 1.1 MB/s eta 0:00:11
     -- ------------------------------------- 0.8/11.9 MB 1.1 MB/s eta 0:00:10
     -- ------------------------------------- 0.8/11.9 MB 1.1 MB/s eta 0:00:10
     -- ------------------------------------- 0.8/11.9 MB 1.1 MB/s eta 0:00:10
     --- ------------------------------------ 1.0/11.9 MB 1.1 MB/s eta 0:00:10
     --- ------------------------------------ 1.0/11.9 MB 1.1 MB/s eta 0:00:10
     --- ------------------------------------ 1.1/11.9 MB 1.1 MB/s eta 0:00:10
     ---- ----------------------------------- 1.2/11.9 MB 1.2 MB/s eta 0:00:10
     ---- ----------------------------------- 1.3/11.9 MB 1.2 MB/s eta 0:00:10
     ---- ----------------------------------- 1.4/11.9 MB 1.2 MB/s eta 0:00:09
     ---- ----------------------------------- 1.5/11.9 MB 1.2 MB/s eta 0:00:09
     ----- ---------------------------------- 1.5/11.9 MB 1.2 MB/s eta 0:00:09
     ----- ---------------------------------- 1.6/11.9 MB 1.2 MB/s eta 0:00:09
     ----- ---------------------------------- 1.6/11.9 MB 1.2 MB/s eta 0:00:09
     ----- ---------------------------------- 1.7/11.9 MB 1.2 MB/s eta 0:00:09
     ------ --------------------------------- 1.8/11.9 MB 1.2 MB/s eta 0:00:09
     ------ --------------------------------- 1.9/11.9 MB 1.2 MB/s eta 0:00:09
     ------ --------------------------------- 2.0/11.9 MB 1.2 MB/s eta 0:00:09
     ------ --------------------------------- 2.1/11.9 MB 1.2 MB/s eta 0:00:09
     ------- -------------------------------- 2.1/11.9 MB 1.2 MB/s eta 0:00:09
     ------- -------------------------------- 2.2/11.9 MB 1.2 MB/s eta 0:00:09
     ------- -------------------------------- 2.3/11.9 MB 1.2 MB/s eta 0:00:09
     -------- ------------------------------- 2.4/11.9 MB 1.2 MB/s eta 0:00:08
     -------- ------------------------------- 2.5/11.9 MB 1.2 MB/s eta 0:00:08
     -------- ------------------------------- 2.6/11.9 MB 1.2 MB/s eta 0:00:08
     -------- ------------------------------- 2.6/11.9 MB 1.2 MB/s eta 0:00:08
     --------- ------------------------------ 2.7/11.9 MB 1.2 MB/s eta 0:00:08
     --------- ------------------------------ 2.7/11.9 MB 1.2 MB/s eta 0:00:08
     --------- ------------------------------ 2.7/11.9 MB 1.2 MB/s eta 0:00:08
     --------- ------------------------------ 2.9/11.9 MB 1.2 MB/s eta 0:00:08
     --------- ------------------------------ 2.9/11.9 MB 1.2 MB/s eta 0:00:08
     ---------- ----------------------------- 3.0/11.9 MB 1.2 MB/s eta 0:00:08
     ---------- ----------------------------- 3.1/11.9 MB 1.2 MB/s eta 0:00:08
     ---------- ----------------------------- 3.2/11.9 MB 1.2 MB/s eta 0:00:08
     ---------- ----------------------------- 3.2/11.9 MB 1.2 MB/s eta 0:00:08
     ----------- ---------------------------- 3.3/11.9 MB 1.2 MB/s eta 0:00:08
     ----------- ---------------------------- 3.4/11.9 MB 1.2 MB/s eta 0:00:08
     ----------- ---------------------------- 3.4/11.9 MB 1.2 MB/s eta 0:00:08
     ----------- ---------------------------- 3.5/11.9 MB 1.2 MB/s eta 0:00:08
     ------------ --------------------------- 3.6/11.9 MB 1.2 MB/s eta 0:00:07
     ------------ --------------------------- 3.7/11.9 MB 1.2 MB/s eta 0:00:07
     ------------ --------------------------- 3.8/11.9 MB 1.2 MB/s eta 0:00:07
     ------------- -------------------------- 3.9/11.9 MB 1.2 MB/s eta 0:00:07
     ------------- -------------------------- 3.9/11.9 MB 1.2 MB/s eta 0:00:07
     ------------- -------------------------- 4.0/11.9 MB 1.2 MB/s eta 0:00:07
     ------------- -------------------------- 4.1/11.9 MB 1.2 MB/s eta 0:00:07
     -------------- ------------------------- 4.2/11.9 MB 1.2 MB/s eta 0:00:07
     -------------- ------------------------- 4.3/11.9 MB 1.2 MB/s eta 0:00:07
     -------------- ------------------------- 4.4/11.9 MB 1.2 MB/s eta 0:00:07
     -------------- ------------------------- 4.4/11.9 MB 1.2 MB/s eta 0:00:07
     --------------- ------------------------ 4.5/11.9 MB 1.2 MB/s eta 0:00:07
     --------------- ------------------------ 4.6/11.9 MB 1.2 MB/s eta 0:00:07
     --------------- ------------------------ 4.6/11.9 MB 1.2 MB/s eta 0:00:07
     ---------------- ----------------------- 4.7/11.9 MB 1.2 MB/s eta 0:00:06
     ---------------- ----------------------- 4.8/11.9 MB 1.2 MB/s eta 0:00:06
     ---------------- ----------------------- 4.9/11.9 MB 1.2 MB/s eta 0:00:06
     ---------------- ----------------------- 5.0/11.9 MB 1.2 MB/s eta 0:00:06
     ----------------- ---------------------- 5.1/11.9 MB 1.2 MB/s eta 0:00:06
     ----------------- ---------------------- 5.1/11.9 MB 1.2 MB/s eta 0:00:06
     ----------------- ---------------------- 5.2/11.9 MB 1.2 MB/s eta 0:00:06
     ----------------- ---------------------- 5.3/11.9 MB 1.2 MB/s eta 0:00:06
     ------------------ --------------------- 5.4/11.9 MB 1.2 MB/s eta 0:00:06
     ------------------ --------------------- 5.4/11.9 MB 1.2 MB/s eta 0:00:06
     ------------------ --------------------- 5.5/11.9 MB 1.2 MB/s eta 0:00:06
     ------------------- -------------------- 5.6/11.9 MB 1.2 MB/s eta 0:00:06
     ------------------- -------------------- 5.7/11.9 MB 1.2 MB/s eta 0:00:06
     ------------------- -------------------- 5.7/11.9 MB 1.2 MB/s eta 0:00:06
     ------------------- -------------------- 5.8/11.9 MB 1.2 MB/s eta 0:00:06
     ------------------- -------------------- 5.8/11.9 MB 1.2 MB/s eta 0:00:06
     ------------------- -------------------- 5.9/11.9 MB 1.2 MB/s eta 0:00:05
     -------------------- ------------------- 5.9/11.9 MB 1.2 MB/s eta 0:00:05
     -------------------- ------------------- 6.0/11.9 MB 1.2 MB/s eta 0:00:05
     -------------------- ------------------- 6.0/11.9 MB 1.2 MB/s eta 0:00:05
     -------------------- ------------------- 6.1/11.9 MB 1.2 MB/s eta 0:00:05
     -------------------- ------------------- 6.1/11.9 MB 1.2 MB/s eta 0:00:05
     -------------------- ------------------- 6.2/11.9 MB 1.2 MB/s eta 0:00:05
     --------------------- ------------------ 6.2/11.9 MB 1.2 MB/s eta 0:00:05
     --------------------- ------------------ 6.3/11.9 MB 1.2 MB/s eta 0:00:05
     --------------------- ------------------ 6.3/11.9 MB 1.2 MB/s eta 0:00:05
     --------------------- ------------------ 6.4/11.9 MB 1.2 MB/s eta 0:00:05
     --------------------- ------------------ 6.4/11.9 MB 1.2 MB/s eta 0:00:05
     --------------------- ------------------ 6.5/11.9 MB 1.2 MB/s eta 0:00:05
     --------------------- ------------------ 6.5/11.9 MB 1.2 MB/s eta 0:00:05
     ---------------------- ----------------- 6.6/11.9 MB 1.2 MB/s eta 0:00:05
     ---------------------- ----------------- 6.6/11.9 MB 1.2 MB/s eta 0:00:05
     ---------------------- ----------------- 6.7/11.9 MB 1.2 MB/s eta 0:00:05
     ---------------------- ----------------- 6.7/11.9 MB 1.2 MB/s eta 0:00:05
     ---------------------- ----------------- 6.8/11.9 MB 1.2 MB/s eta 0:00:05
     ---------------------- ----------------- 6.8/11.9 MB 1.2 MB/s eta 0:00:05
     ----------------------- ---------------- 6.9/11.9 MB 1.2 MB/s eta 0:00:05
     ----------------------- ---------------- 6.9/11.9 MB 1.2 MB/s eta 0:00:05
     ----------------------- ---------------- 7.0/11.9 MB 1.2 MB/s eta 0:00:05
     ----------------------- ---------------- 7.0/11.9 MB 1.2 MB/s eta 0:00:05
     ----------------------- ---------------- 7.1/11.9 MB 1.2 MB/s eta 0:00:04
     ----------------------- ---------------- 7.1/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------ --------------- 7.1/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------ --------------- 7.2/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------ --------------- 7.2/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------ --------------- 7.3/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------ --------------- 7.3/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------ --------------- 7.4/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------- -------------- 7.4/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------- -------------- 7.5/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------- -------------- 7.5/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------- -------------- 7.6/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------- -------------- 7.6/11.9 MB 1.2 MB/s eta 0:00:04
     -------------------------- ------------- 7.7/11.9 MB 1.2 MB/s eta 0:00:04
     -------------------------- ------------- 7.8/11.9 MB 1.2 MB/s eta 0:00:04
     -------------------------- ------------- 7.9/11.9 MB 1.2 MB/s eta 0:00:04
     -------------------------- ------------- 7.9/11.9 MB 1.2 MB/s eta 0:00:04
     --------------------------- ------------ 8.0/11.9 MB 1.2 MB/s eta 0:00:04
     --------------------------- ------------ 8.1/11.9 MB 1.2 MB/s eta 0:00:04
     --------------------------- ------------ 8.1/11.9 MB 1.2 MB/s eta 0:00:04
     --------------------------- ------------ 8.2/11.9 MB 1.2 MB/s eta 0:00:04
     --------------------------- ------------ 8.3/11.9 MB 1.2 MB/s eta 0:00:03
     --------------------------- ------------ 8.3/11.9 MB 1.2 MB/s eta 0:00:03
     --------------------------- ------------ 8.3/11.9 MB 1.2 MB/s eta 0:00:03
     ---------------------------- ----------- 8.4/11.9 MB 1.2 MB/s eta 0:00:03
     ---------------------------- ----------- 8.5/11.9 MB 1.2 MB/s eta 0:00:03
     ----------------------------- ---------- 8.6/11.9 MB 1.2 MB/s eta 0:00:03
     ----------------------------- ---------- 8.7/11.9 MB 1.2 MB/s eta 0:00:03
     ----------------------------- ---------- 8.7/11.9 MB 1.2 MB/s eta 0:00:03
     ----------------------------- ---------- 8.8/11.9 MB 1.2 MB/s eta 0:00:03
     ----------------------------- ---------- 8.9/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------ --------- 8.9/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------ --------- 9.0/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------ --------- 9.1/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------- -------- 9.2/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------- -------- 9.3/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------- -------- 9.4/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------- -------- 9.4/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------- -------- 9.5/11.9 MB 1.2 MB/s eta 0:00:02
     -------------------------------- ------- 9.5/11.9 MB 1.2 MB/s eta 0:00:02
     -------------------------------- ------- 9.5/11.9 MB 1.2 MB/s eta 0:00:02
     -------------------------------- ------- 9.7/11.9 MB 1.2 MB/s eta 0:00:02
     -------------------------------- ------- 9.7/11.9 MB 1.2 MB/s eta 0:00:02
     --------------------------------- ------ 9.9/11.9 MB 1.2 MB/s eta 0:00:02
     --------------------------------- ------ 10.0/11.9 MB 1.2 MB/s eta 0:00:02
     ---------------------------------- ----- 10.1/11.9 MB 1.2 MB/s eta 0:00:02
     ---------------------------------- ----- 10.2/11.9 MB 1.2 MB/s eta 0:00:02
     ---------------------------------- ----- 10.3/11.9 MB 1.2 MB/s eta 0:00:02
     ---------------------------------- ----- 10.3/11.9 MB 1.2 MB/s eta 0:00:02
     ----------------------------------- ---- 10.5/11.9 MB 1.2 MB/s eta 0:00:02
     ----------------------------------- ---- 10.6/11.9 MB 1.2 MB/s eta 0:00:02
     ----------------------------------- ---- 10.6/11.9 MB 1.2 MB/s eta 0:00:02
     ------------------------------------ --- 10.7/11.9 MB 1.2 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 1.2 MB/s eta 0:00:01
     ------------------------------------ --- 10.8/11.9 MB 1.2 MB/s eta 0:00:01
     ------------------------------------ --- 10.9/11.9 MB 1.2 MB/s eta 0:00:01
     ------------------------------------ --- 10.9/11.9 MB 1.2 MB/s eta 0:00:01
     ------------------------------------ --- 10.9/11.9 MB 1.2 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 1.2 MB/s eta 0:00:01
     ------------------------------------- -- 11.1/11.9 MB 1.2 MB/s eta 0:00:01
     ------------------------------------- -- 11.1/11.9 MB 1.2 MB/s eta 0:00:01
     ------------------------------------- -- 11.1/11.9 MB 1.2 MB/s eta 0:00:01
     ------------------------------------- -- 11.1/11.9 MB 1.1 MB/s eta 0:00:01
     ------------------------------------- -- 11.2/11.9 MB 1.1 MB/s eta 0:00:01
     ------------------------------------- -- 11.2/11.9 MB 1.1 MB/s eta 0:00:01
     ------------------------------------- -- 11.2/11.9 MB 1.1 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 1.1 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 1.1 MB/s eta 0:00:01
     -------------------------------------- - 11.4/11.9 MB 1.1 MB/s eta 0:00:01
     -------------------------------------- - 11.4/11.9 MB 1.1 MB/s eta 0:00:01
     -------------------------------------- - 11.4/11.9 MB 1.1 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 1.1 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 1.1 MB/s eta 0:00:01
     -------------------------------------- - 11.6/11.9 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------  11.6/11.9 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------  11.7/11.9 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------  11.7/11.9 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 1.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py): started
  Building wheel for mysql.connector (setup.py): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-win_amd64.whl size=247958 sha256=0f18c9750f2cbbe9e6a899eb101afa185431f5d2c97215859e82b5711a77d464
  Stored in directory: c:\users\tanvir ahmed\appdata\local\pip\cache\wheels\03\17\fa\d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [4]:
# code here
import mysql.connector
con=mysql.connector.connect(host='localhost',user='root',password='',database='supermarket')

In [5]:
df1=pd.read_sql_query("select * from invoices",con)
df1.head()

C:\Users\Tanvir Ahmed\AppData\Local\Temp\ipykernel_13380\3530349411.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df1=pd.read_sql_query("select * from invoices",con)

,Order Id,Date,Meal Id,Company Id,Date of Meal,Participants,Meal Price,Type of Meal
0,839FKFW2LLX4LMBB,27-05-2016,INBUX904GIHI8YBD,LJKS5NK6788CYMUU,2016-05-31 07:00:00+02:00,['David Bishop'],469,Breakfast
1,97OX39BGVMHODLJM,27-09-2018,J0MMOOPP709DIDIE,LJKS5NK6788CYMUU,2018-10-01 20:00:00+02:00,['David Bishop'],22,Dinner
2,041ORQM5OIHTIU6L,24-08-2014,E4UJLQNCI16UX5CS,LJKS5NK6788CYMUU,2014-08-23 14:00:00+02:00,['Karen Stansell'],314,Lunch
3,YT796QI18WNGZ7ZJ,2014-12-04 00:00:00,C9SDFHF7553BE247,LJKS5NK6788CYMUU,2014-04-07 21:00:00+02:00,['Addie Patino'],438,Dinner
4,6YLROQT27B6HRF4E,28-07-2015,48EQXS6IHYNZDDZ5,LJKS5NK6788CYMUU,2015-07-27 14:00:00+02:00,['Addie Patino' 'Susan Guerrero'],690,Lunch

In [7]:
df2=pd.read_sql_query("select * from orderleads", con)
df2.head()

C:\Users\Tanvir Ahmed\AppData\Local\Temp\ipykernel_13380\2044157259.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2=pd.read_sql_query("select * from orderleads", con)

,Order Id,Company Id,Company Name,Date,Order Value,Converted
0,80EYLOKP9E762WKG,LJKS5NK6788CYMUU,Chimera-Chasing Casbah,18-02-2017,4875,1
1,TLEXR1HZWTUTBHPB,LJKS5NK6788CYMUU,Chimera-Chasing Casbah,30-07-2015,8425,0
2,839FKFW2LLX4LMBB,LJKS5NK6788CYMUU,Chimera-Chasing Casbah,27-05-2016,4837,0
3,97OX39BGVMHODLJM,LJKS5NK6788CYMUU,Chimera-Chasing Casbah,27-09-2018,343,0
4,5T4LGH4XGBWOD49Z,LJKS5NK6788CYMUU,Chimera-Chasing Casbah,14-01-2016,983,0

In [8]:
df3=pd.read_sql_query("select * from salesteam",con)
df3.head()

C:\Users\Tanvir Ahmed\AppData\Local\Temp\ipykernel_13380\2034583703.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df3=pd.read_sql_query("select * from salesteam",con)

,Sales Rep,Sales Rep Id,Company Name,Company Id
0,Jessie Mcallister,97UNNAT790E0WM4N,Chimera-Chasing Casbah,LJKS5NK6788CYMUU
1,Jessie Mcallister,97UNNAT790E0WM4N,Tangential Sheds,36MFTZOYMTAJP1RK
2,Jessie Mcallister,97UNNAT790E0WM4N,Two-Mile Grab,H3JRC7XX7WJAD4ZO
3,Jessie Mcallister,97UNNAT790E0WM4N,Three-Men-And-A-Helper Congo'S,HB25MDZR0MGCQUGX
4,Jessie Mcallister,97UNNAT790E0WM4N,Biophysical Battleground,7RVA8TIVBLBXMNO4

In [10]:
df1.to_excel("Supermarket.xlsx",sheet_name="invoices")

In [12]:
with pd.ExcelWriter("Supermarket.xlsx") as w:
    df1.to_excel(w,sheet_name='invoices')
    df2.to_excel(w,sheet_name='order_leads')
    df3.to_excel(w,sheet_name="salesteam")

### Problem-2

Go to the site: https://rapidapi.com/wirefreethought/api/geodb-cities. From here, you have to grab the API and have to choose proper routes to get the cities of different countries. After getting the right API, hit that API and create a dataframe of all the cities that you can get by using the API. Then store the dataframe to a SQL. If you need to create an account or have to subscribe, then do that (it has free subscription but has some limitations. Use that free subscription and modify your accordingly to get all the data).

In [14]:
### code here
url = "https://wft-geo-db.p.rapidapi.com/v1/geo/places/%7BplaceId%7D/distance"

querystring = {"toPlaceId":"Q60"}

headers = {
	"x-rapidapi-key": "972e3a70d9mshe4d3769d53ab17ep18c971jsnd0ba60e5a582",
	"x-rapidapi-host": "wft-geo-db.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'errors': [{'type': 'WftWsError.NotFound', 'code': 'NOT_FOUND', 'message': "Place with id '{placeId}' not found"}]}

### Problem 3:

Go to this url: https://www.flipkart.com/search?q=smartphones. This is the url to find phones in flipkart website. You have to extract the below things:
1. image url of the phone
2. name of the image
3. average ratings
4. total ratings
5. total reviews
6. discounted price
7. actual price

Extract all the phones which are available in this website. So you have to use the pagination concept. **Also after requesting every page through the url, please wait for a while (minimum 2-3 seconds), otherwise your IP address can be banned to access the flipkart website later.**

After collecting all the data, save that in a JSON file.

In [31]:
# code here
url="https://www.flipkart.com/search?q=smartphones&page=1"
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
res=requests.get(url,headers=headers).text
res

'<!doctype html><html lang="en"><head><link href="https://rukminim2.flixcart.com" rel="preconnect"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.aa1465.css"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.fbaef9.css"/><meta http-equiv="Content-type" content="text/html; charset=utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=Edge"/><meta property="fb:page_id" content="102988293558"/><meta property="fb:admins" content="658873552,624500995,100000233612389"/><link rel="shortcut icon" href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico"/><link type="application/opensearchdescription+xml" rel="search" href="/osdd.xml?v=2"/><meta property="og:type" content="website"/><meta name="og_site_name" property="og:site_name" content="Flipkart.com"/><link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png"/><link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png"/><link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png"/><link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png"/><link rel="apple-touch-icon" href="/apple-touch-icon-57x57.png"/><meta name="twitter:card" content="app"><meta name="twitter:site" content="@flipkart"><meta name="twitter:creator" content="@flipkart"><meta name="twitter:title" content="Smartphones- Buy Products Online at Best Price in India - All Categories | Flipkart.com"><meta name="twitter:description" content="Shop for electronics, apparels & more using our Flipkart app Free shipping & COD."><meta name="twitter:app:country" content="in"><meta name="al:ios:app_name" content="Flipkart"><meta name="al:ios:app_store_id" content="742044692"><meta name="twitter:app:name:iphone" content="Flipkart"><meta name="twitter:app:id:iphone" content="742044692"><meta name="twitter:app:url:iphone" content="http://dl.flipkart.com/dl/home?"><meta name="twitter:app:name:ipad" content="Flipkart"><meta name="twitter:app:id:ipad" content="742044692"><meta name="twitter:app:url:ipad" content="http://dl.flipkart.com/dl/home?"><meta name="twitter:app:name:googleplay" content="Flipkart"><meta name="twitter:app:id:googleplay" content="com.flipkart.android"><meta name="twitter:app:url:googleplay" content="http://dl.flipkart.com/dl/home?"><style>#container {\n\t\t\theight: 100%;\n\t\t}</style> <script src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/runtime.14f2c17a.js" defer="defer" crossorigin="anonymous"></script><script src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/vendor.79dfd802.js" defer="defer" crossorigin="anonymous"></script><script src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_common.3b9e09f1.js" defer="defer" crossorigin="anonymous"></script><script src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_modules.e2a4f33c.js" defer="defer" crossorigin="anonymous"></script><script src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app.de59d551.js" defer="defer" crossorigin="anonymous"></script> <link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/Browse.chunk.647087.css"/><title>Smartphones- Buy Products Online at Best Price in India - All Categories | Flipkart.com</title><meta name="og_title" property="og:title" content="Smartphones- Buy Products Online at Best Price in India - All Categories | Flipkart.com"/><meta name="Keywords" content="Smartphones"/> <meta name="Description" content="Smartphones- Buy Products Online at Best Price in India. India&#x27;s Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com"/><meta property="og:description" content="Smartphones- Buy Products Online at Best Price in India. India&#x27;s Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com"/>       <meta name="msvalidate.01" content="F4EEB3A0AFFDD385992A06E6920C0AC3"/> <!--[if IE 9 ]>\n\t<script nonce="3945662651995770124">\n\t\twindow.browserVersion = \'IE9\';\n\t\tdocument.documentElement.className += \' ie9\';\n\t</script>\n\t<![endif]--><!--[if !IE]><!--><script nonce="3945662651995770124">if (/*@cc_on!@*/false) {\n\t\t\twindow.browserVersion = \'IE10\';\n\t\t\tdocument.documentElement.className += \' ie10\';\n\t\t}</script><!--<![endif]--> <script nonce="3945662651995770124">;window.NREUM||(NREUM={});NREUM.init={distributed_tracing:{enabled:true},privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]}};\n\n\t\t\t;NREUM.loader_config={accountID:"3700282",trustKey:"3679896",agentID:"1588759528",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528"}\n\t\t\t;NREUM.info={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528",sa:1}\n\n\t\t\t;/*! For license information please see nr-loader-spa-1.236.0.min.js.LICENSE.txt */\n\t\t\t(()=>{"use strict";var e,t,r={5763:(e,t,r)=>{r.d(t,{P_:()=>l,Mt:()=>g,C5:()=>s,DL:()=>v,OP:()=>T,lF:()=>D,Yu:()=>y,Dg:()=>h,CX:()=>c,GE:()=>b,sU:()=>_});var n=r(8632),i=r(9567);const o={beacon:n.ce.beacon,errorBeacon:n.ce.errorBeacon,licenseKey:void 0,applicationID:void 0,sa:void 0,queueTime:void 0,applicationTime:void 0,ttGuid:void 0,user:void 0,account:void 0,product:void 0,extra:void 0,jsAttributes:{},userAttributes:void 0,atts:void 0,transactionName:void 0,tNamePlain:void 0},a={};function s(e){if(!e)throw new Error("All info objects require an agent identifier!");if(!a[e])throw new Error("Info for ".concat(e," was never set"));return a[e]}function c(e,t){if(!e)throw new Error("All info objects require an agent identifier!");a[e]=(0,i.D)(t,o),(0,n.Qy)(e,a[e],"info")}var u=r(7056);const d=()=>{const e={blockSelector:"[data-nr-block]",maskInputOptions:{password:!0}};return{allow_bfcache:!0,privacy:{cookies_enabled:!0},ajax:{deny_list:void 0,enabled:!0,harvestTimeSeconds:10},distributed_tracing:{enabled:void 0,exclude_newrelic_header:void 0,cors_use_newrelic_header:void 0,cors_use_tracecontext_headers:void 0,allowed_origins:void 0},session:{domain:void 0,expiresMs:u.oD,inactiveMs:u.Hb},ssl:void 0,obfuscate:void 0,jserrors:{enabled:!0,harvestTimeSeconds:10},metrics:{enabled:!0},page_action:{enabled:!0,harvestTimeSeconds:30},page_view_event:{enabled:!0},page_view_timing:{enabled:!0,harvestTimeSeconds:30,long_task:!1},session_trace:{enabled:!0,harvestTimeSeconds:10},harvest:{tooManyRequestsDelay:60},session_replay:{enabled:!1,harvestTimeSeconds:60,sampleRate:.1,errorSampleRate:.1,maskTextSelector:"*",maskAllInputs:!0,get blockClass(){return"nr-block"},get ignoreClass(){return"nr-ignore"},get maskTextClass(){return"nr-mask"},get blockSelector(){return e.blockSelector},set blockSelector(t){e.blockSelector+=",".concat(t)},get maskInputOptions(){return e.maskInputOptions},set maskInputOptions(t){e.maskInputOptions={...t,password:!0}}},spa:{enabled:!0,harvestTimeSeconds:10}}},f={};function l(e){if(!e)throw new Error("All configuration objects require an agent identifier!");if(!f[e])throw new Error("Configuration for ".concat(e," was never set"));return f[e]}function h(e,t){if(!e)throw new Error("All configuration objects require an agent identifier!");f[e]=(0,i.D)(t,d()),(0,n.Qy)(e,f[e],"config")}function g(e,t){if(!e)throw new Error("All configuration objects require an agent identifier!");var r=l(e);if(r){for(var n=t.split("."),i=0;i<n.length-1;i++)if("object"!=typeof(r=r[n[i]]))return;r=r[n[n.length-1]]}return r}const p={accountID:void 0,trustKey:void 0,agentID:void 0,licenseKey:void 0,applicationID:void 0,xpid:void 0},m={};function v(e){if(!e)throw new Error("All loader-config objects require an agent identifier!");if(!m[e])throw new Error("LoaderConfig for ".concat(e," was never set"));return m[e]}function b(e,t){if(!e)throw new Error("All loader-config objects require an agent identifier!");m[e]=(0,i.D)(t,p),(0,n.Qy)(e,m[e],"loader_config")}const y=(0,n.mF)().o;var w=r(385),x=r(6818);const A={buildEnv:x.Re,bytesSent:{},queryBytesSent:{},customTransaction:void 0,disabled:!1,distMethod:x.gF,isolatedBacklog:!1,loaderType:void 0,maxBytes:3e4,offset:Math.floor(w._A?.performance?.timeOrigin||w._A?.performance?.timing?.navigationStart||Date.now()),onerror:void 0,origin:""+w._A.location,ptid:void 0,releaseIds:{},session:void 0,xhrWrappable:"function"==typeof w._A.XMLHttpRequest?.prototype?.addEventListener,version:x.q4},E={};function T(e){if(!e)throw new Error("All runtime objects require an agent identifier!");if(!E[e])throw new Error("Runtime for ".concat(e," was never set"));return E[e]}function _(e,t){if(!e)throw new Error("All runtime objects require an agent identifier!");E[e]=(0,i.D)(t,A),(0,n.Qy)(e,E[e],"runtime")}function D(e){return function(e){try{const t=s(e);return!!t.licenseKey&&!!t.errorBeacon&&!!t.applicationID}catch(e){return!1}}(e)}},9567:(e,t,r)=>{r.d(t,{D:()=>i});var n=r(50);function i(e,t){try{if(!e||"object"!=typeof e)return(0,n.Z)("Setting a Configurable requires an object as input");if(!t||"object"!=typeof t)return(0,n.Z)("Setting a Configurable requires a model to set its initial properties");const r=Object.create(Object.getPrototypeOf(t),Object.getOwnPropertyDescriptors(t)),o=0===Object.keys(r).length?e:r;for(let a in o)if(void 0!==e[a])try{"object"==typeof e[a]&&"object"==typeof t[a]?r[a]=i(e[a],t[a]):r[a]=e[a]}catch(e){(0,n.Z)("An error occurred while setting a property of a Configurable",e)}return r}catch(e){(0,n.Z)("An error occured while setting a Configurable",e)}}},6818:(e,t,r)=>{r.d(t,{Re:()=>i,gF:()=>o,q4:()=>n});const n="1.236.0",i="PROD",o="CDN"},385:(e,t,r)=>{r.d(t,{FN:()=>a,IF:()=>u,Nk:()=>f,Tt:()=>s,_A:()=>o,il:()=>n,pL:()=>c,v6:()=>i,w1:()=>d});const n="undefined"!=typeof window&&!!window.document,i="undefined"!=typeof WorkerGlobalScope&&("undefined"!=typeof self&&self instanceof WorkerGlobalScope&&self.navigator instanceof WorkerNavigator||"undefined"!=typeof globalThis&&globalThis instanceof WorkerGlobalScope&&globalThis.navigator instanceof WorkerNavigator),o=n?window:"undefined"!=typeof WorkerGlobalScope&&("undefined"!=typeof self&&self instanceof WorkerGlobalScope&&self||"undefined"!=typeof globalThis&&globalThis instanceof WorkerGlobalScope&&globalThis),a=""+o?.location,s=/iPad|iPhone|iPod/.test(navigator.userAgent),c=s&&"undefined"==typeof SharedWorker,u=(()=>{const e=navigator.userAgent.match(/Firefox[/\\s](\\d+\\.\\d+)/);return Array.isArray(e)&&e.length>=2?+e[1]:0})(),d=Boolean(n&&window.document.documentMode),f=!!navigator.sendBeacon},1117:(e,t,r)=>{r.d(t,{w:()=>o});var n=r(50);const i={agentIdentifier:"",ee:void 0};class o{constructor(e){try{if("object"!=typeof e)return(0,n.Z)("shared context requires an object as input");this.sharedContext={},Object.assign(this.sharedContext,i),Object.entries(e).forEach((e=>{let[t,r]=e;Object.keys(i).includes(t)&&(this.sharedContext[t]=r)}))}catch(e){(0,n.Z)("An error occured while setting SharedContext",e)}}}},8e3:(e,t,r)=>{r.d(t,{L:()=>d,R:()=>c});var n=r(2177),i=r(1284),o=r(4322),a=r(3325);const s={};function c(e,t){const r={staged:!1,priority:a.p[t]||0};u(e),s[e].get(t)||s[e].set(t,r)}function u(e){e&&(s[e]||(s[e]=new Map))}function d(){let e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:"",t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"feature";if(u(e),!e||!s[e].get(t))return a(t);s[e].get(t).staged=!0;const r=[...s[e]];function a(t){const r=e?n.ee.get(e):n.ee,a=o.X.handlers;if(r.backlog&&a){var s=r.backlog[t],c=a[t];if(c){for(var u=0;s&&u<s.length;++u)f(s[u],c);(0,i.D)(c,(function(e,t){(0,i.D)(t,(function(t,r){r[0].on(e,r[1])}))}))}delete a[t],r.backlog[t]=null,r.emit("drain-"+t,[])}}r.every((e=>{let[t,r]=e;return r.staged}))&&(r.sort(((e,t)=>e[1].priority-t[1].priority)),r.forEach((e=>{let[t]=e;a(t)})))}function f(e,t){var r=e[1];(0,i.D)(t[r],(function(t,r){var n=e[0];if(r[0]===n){var i=r[1],o=e[3],a=e[2];i.apply(o,a)}}))}},2177:(e,t,r)=>{r.d(t,{c:()=>f,ee:()=>u});var n=r(8632),i=r(2210),o=r(1284),a=r(5763),s="nr@context";let c=(0,n.fP)();var u;function d(){}function f(e){return(0,i.X)(e,s,l)}function l(){return new d}function h(){u.aborted=!0,u.backlog={}}c.ee?u=c.ee:(u=function e(t,r){var n={},c={},f={},g=!1;try{g=16===r.length&&(0,a.OP)(r).isolatedBacklog}catch(e){}var p={on:b,addEventListener:b,removeEventListener:y,emit:v,get:x,listeners:w,context:m,buffer:A,abort:h,aborted:!1,isBuffering:E,debugId:r,backlog:g?{}:t&&"object"==typeof t.backlog?t.backlog:{}};return p;function m(e){return e&&e instanceof d?e:e?(0,i.X)(e,s,l):l()}function v(e,r,n,i,o){if(!1!==o&&(o=!0),!u.aborted||i){t&&o&&t.emit(e,r,n);for(var a=m(n),s=w(e),d=s.length,f=0;f<d;f++)s[f].apply(a,r);var l=T()[c[e]];return l&&l.push([p,e,r,a]),a}}function b(e,t){n[e]=w(e).concat(t)}function y(e,t){var r=n[e];if(r)for(var i=0;i<r.length;i++)r[i]===t&&r.splice(i,1)}function w(e){return n[e]||[]}function x(t){return f[t]=f[t]||e(p,t)}function A(e,t){var r=T();p.aborted||(0,o.D)(e,(function(e,n){t=t||"feature",c[n]=t,t in r||(r[t]=[])}))}function E(e){return!!T()[c[e]]}function T(){return p.backlog}}(void 0,"globalEE"),c.ee=u)},5546:(e,t,r)=>{r.d(t,{E:()=>n,p:()=>i});var n=r(2177).ee.get("handle");function i(e,t,r,i,o){o?(o.buffer([e],i),o.emit(e,t,r)):(n.buffer([e],i),n.emit(e,t,r))}},4322:(e,t,r)=>{r.d(t,{X:()=>o});var n=r(5546);o.on=a;var i=o.handlers={};function o(e,t,r,o){a(o||n.E,i,e,t,r)}function a(e,t,r,i,o){o||(o="feature"),e||(e=n.E);var a=t[o]=t[o]||{};(a[r]=a[r]||[]).push([e,i])}},3239:(e,t,r)=>{r.d(t,{bP:()=>s,iz:()=>c,m$:()=>a});var n=r(385);let i=!1,o=!1;try{const e={get passive(){return i=!0,!1},get signal(){return o=!0,!1}};n._A.addEventListener("test",null,e),n._A.removeEventListener("test",null,e)}catch(e){}function a(e,t){return i||o?{capture:!!e,passive:i,signal:t}:!!e}function s(e,t){let r=arguments.length>2&&void 0!==arguments[2]&&arguments[2],n=arguments.length>3?arguments[3]:void 0;window.addEventListener(e,t,a(r,n))}function c(e,t){let r=arguments.length>2&&void 0!==arguments[2]&&arguments[2],n=arguments.length>3?arguments[3]:void 0;document.addEventListener(e,t,a(r,n))}},4402:(e,t,r)=>{r.d(t,{Ht:()=>u,M:()=>c,Rl:()=>a,ky:()=>s});var n=r(385);const i="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx";function o(e,t){return e?15&e[t]:16*Math.random()|0}function a(){const e=n._A?.crypto||n._A?.msCrypto;let t,r=0;return e&&e.getRandomValues&&(t=e.getRandomValues(new Uint8Array(31))),i.split("").map((e=>"x"===e?o(t,++r).toString(16):"y"===e?(3&o()|8).toString(16):e)).join("")}function s(e){const t=n._A?.crypto||n._A?.msCrypto;let r,i=0;t&&t.getRandomValues&&(r=t.getRandomValues(new Uint8Array(31)));const a=[];for(var s=0;s<e;s++)a.push(o(r,++i).toString(16));return a.join("")}function c(){return s(16)}function u(){return s(32)}},7056:(e,t,r)=>{r.d(t,{Bq:()=>n,Hb:()=>o,oD:()=>i});const n="NRBA",i=144e5,o=18e5},7894:(e,t,r)=>{function n(){return Math.round(performance.now())}r.d(t,{z:()=>n})},7243:(e,t,r)=>{r.d(t,{e:()=>o});var n=r(385),i={};function o(e){if(e in i)return i[e];if(0===(e||"").indexOf("data:"))return{protocol:"data"};let t;var r=n._A?.location,o={};if(n.il)t=document.createElement("a"),t.href=e;else try{t=new URL(e,r.href)}catch(e){return o}o.port=t.port;var a=t.href.split("://");!o.port&&a[1]&&(o.port=a[1].split("/")[0].split("@").pop().split(":")[1]),o.port&&"0"!==o.port||(o.port="https"===a[0]?"443":"80"),o.hostname=t.hostname||r.hostname,o.pathname=t.pathname,o.protocol=a[0],"/"!==o.pathname.charAt(0)&&(o.pathname="/"+o.pathname);var s=!t.protocol||":"===t.protocol||t.protocol===r.protocol,c=t.hostname===r.hostname&&t.port===r.port;return o.sameOrigin=s&&(!t.hostname||c),"/"===o.pathname&&(i[e]=o),o}},50:(e,t,r)=>{function n(e,t){"function"==typeof console.warn&&(console.warn("New Relic: ".concat(e)),t&&console.warn(t))}r.d(t,{Z:()=>n})},2587:(e,t,r)=>{r.d(t,{N:()=>c,T:()=>u});var n=r(2177),i=r(5546),o=r(8e3),a=r(3325);const s={stn:[a.D.sessionTrace],err:[a.D.jserrors,a.D.metrics],ins:[a.D.pageAction],spa:[a.D.spa],sr:[a.D.sessionReplay,a.D.sessionTrace]};function c(e,t){const r=n.ee.get(t);e&&"object"==typeof e&&(Object.entries(e).forEach((e=>{let[t,n]=e;void 0===u[t]&&(s[t]?s[t].forEach((e=>{n?(0,i.p)("feat-"+t,[],void 0,e,r):(0,i.p)("block-"+t,[],void 0,e,r),(0,i.p)("rumresp-"+t,[Boolean(n)],void 0,e,r)})):n&&(0,i.p)("feat-"+t,[],void 0,void 0,r),u[t]=Boolean(n))})),Object.keys(s).forEach((e=>{void 0===u[e]&&(s[e]?.forEach((t=>(0,i.p)("rumresp-"+e,[!1],void 0,t,r))),u[e]=!1)})),(0,o.L)(t,a.D.pageViewEvent))}const u={}},2210:(e,t,r)=>{r.d(t,{X:()=>i});var n=Object.prototype.hasOwnProperty;function i(e,t,r){if(n.call(e,t))return e[t];var i=r();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(e,t,{value:i,writable:!0,enumerable:!1}),i}catch(e){}return e[t]=i,i}},1284:(e,t,r)=>{r.d(t,{D:()=>n});const n=(e,t)=>Object.entries(e||{}).map((e=>{let[r,n]=e;return t(r,n)}))},4351:(e,t,r)=>{r.d(t,{P:()=>o});var n=r(2177);const i=()=>{const e=new WeakSet;return(t,r)=>{if("object"==typeof r&&null!==r){if(e.has(r))return;e.add(r)}return r}};function o(e){try{return JSON.stringify(e,i())}catch(e){try{n.ee.emit("internal-error",[e])}catch(e){}}}},3960:(e,t,r)=>{r.d(t,{K:()=>a,b:()=>o});var n=r(3239);function i(){return"undefined"==typeof document||"complete"===document.readyState}function o(e,t){if(i())return e();(0,n.bP)("load",e,t)}function a(e){if(i())return e();(0,n.iz)("DOMContentLoaded",e)}},8632:(e,t,r)=>{r.d(t,{EZ:()=>u,Qy:()=>c,ce:()=>o,fP:()=>a,gG:()=>d,mF:()=>s});var n=r(7894),i=r(385);const o={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net"};function a(){return i._A.NREUM||(i._A.NREUM={}),void 0===i._A.newrelic&&(i._A.newrelic=i._A.NREUM),i._A.NREUM}function s(){let e=a();return e.o||(e.o={ST:i._A.setTimeout,SI:i._A.setImmediate,CT:i._A.clearTimeout,XHR:i._A.XMLHttpRequest,REQ:i._A.Request,EV:i._A.Event,PR:i._A.Promise,MO:i._A.MutationObserver,FETCH:i._A.fetch}),e}function c(e,t,r){let i=a();const o=i.initializedAgents||{},s=o[e]||{};return Object.keys(s).length||(s.initializedAt={ms:(0,n.z)(),date:new Date}),i.initializedAgents={...o,[e]:{...s,[r]:t}},i}function u(e,t){a()[e]=t}function d(){return function(){let e=a();const t=e.info||{};e.info={beacon:o.beacon,errorBeacon:o.errorBeacon,...t}}(),function(){let e=a();const t=e.init||{};e.init={...t}}(),s(),function(){let e=a();const t=e.loader_config||{};e.loader_config={...t}}(),a()}},7956:(e,t,r)=>{r.d(t,{N:()=>i});var n=r(3239);function i(e){let t=arguments.length>1&&void 0!==arguments[1]&&arguments[1],r=arguments.length>2?arguments[2]:void 0,i=arguments.length>3?arguments[3]:void 0;return void(0,n.iz)("visibilitychange",(function(){if(t)return void("hidden"==document.visibilityState&&e());e(document.visibilityState)}),r,i)}},1214:(e,t,r)=>{r.d(t,{em:()=>v,u5:()=>N,QU:()=>S,_L:()=>I,Gm:()=>L,Lg:()=>M,gy:()=>U,BV:()=>Q,Kf:()=>ee});var n=r(2177);const i="nr@original";var o=Object.prototype.hasOwnProperty,a=!1;function s(e,t){return e||(e=n.ee),r.inPlace=function(e,t,n,i,o){n||(n="");var a,s,c,u="-"===n.charAt(0);for(c=0;c<t.length;c++)d(a=e[s=t[c]])||(e[s]=r(a,u?s+n:n,i,s,o))},r.flag=i,r;function r(t,r,n,a,s){return d(t)?t:(r||(r=""),nrWrapper[i]=t,u(t,nrWrapper,e),nrWrapper);function nrWrapper(){var i,u,d,f;try{u=this,i=[...arguments],d="function"==typeof n?n(i,u):n||{}}catch(t){c([t,"",[i,u,a],d],e)}o(r+"start",[i,u,a],d,s);try{return f=t.apply(u,i)}catch(e){throw o(r+"err",[i,u,e],d,s),e}finally{o(r+"end",[i,u,f],d,s)}}}function o(r,n,i,o){if(!a||t){var s=a;a=!0;try{e.emit(r,n,i,t,o)}catch(t){c([t,r,n,i],e)}a=s}}}function c(e,t){t||(t=n.ee);try{t.emit("internal-error",e)}catch(e){}}function u(e,t,r){if(Object.defineProperty&&Object.keys)try{return Object.keys(e).forEach((function(r){Object.defineProperty(t,r,{get:function(){return e[r]},set:function(t){return e[r]=t,t}})})),t}catch(e){c([e],r)}for(var n in e)o.call(e,n)&&(t[n]=e[n]);return t}function d(e){return!(e&&e instanceof Function&&e.apply&&!e[i])}var f=

In [ ]:
requests.get(url).text #capcha problem

'<!DOCTYPE html><html lang=en><meta charset=UTF-8><meta content="width=device-width,initial-scale=1"name=viewport><title>Flipkart reCAPTCHA</title><link href=https://static-assets-web.flixcart.com/batman-returns/batman-returns/s/recaptcha.css rel=stylesheet><script src="https://www.google.com/recaptcha/enterprise.js?render=6Lc49B0pAAAAAIVgOhfwW8i7t7SRO0KSnlSVZRAq"></script><script src=https://static-assets-web.flixcart.com/apex-static/js/recaptcha-enterprise-v1.js async defer></script><div class=container><img alt="Flipkart Logo"class=logo src="https://rukminim1.flixcart.com/www/60/60/promos/14/06/2024/88011666-ce1d-40f0-a8eb-1bac7d164885.png?q=60"><h1 class=header>Are you a human?</h1><p class=subText>Confirming...<div class=loaderContainer><div class=loader></div></div></div>'

In [19]:
from bs4 import BeautifulSoup

In [36]:
soup=BeautifulSoup(res,'html.parser')
soup

<!DOCTYPE html>
<html lang="en"><head><link href="https://rukminim2.flixcart.com" rel="preconnect"/><link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.aa1465.css" rel="stylesheet"/><link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.fbaef9.css" rel="stylesheet"/><meta content="text/html; charset=utf-8" http-equiv="Content-type"/><meta content="IE=Edge" http-equiv="X-UA-Compatible"/><meta content="102988293558" property="fb:page_id"/><meta content="658873552,624500995,100000233612389" property="fb:admins"/><link href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico" rel="shortcut icon"/><link href="/osdd.xml?v=2" rel="search" type="application/opensearchdescription+xml"/><meta content="website" property="og:type"/><meta content="Flipkart.com" name="og_site_name" property="og:site_name"/><link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/><link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/><link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/><link href="/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/><link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon"/><meta content="app" name="twitter:card"/><meta content="@flipkart" name="twitter:site"/><meta content="@flipkart" name="twitter:creator"/><meta content="Smartphones- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="twitter:title"/><meta content="Shop for electronics, apparels &amp; more using our Flipkart app Free shipping &amp; COD." name="twitter:description"/><meta content="in" name="twitter:app:country"/><meta content="Flipkart" name="al:ios:app_name"/><meta content="742044692" name="al:ios:app_store_id"/><meta content="Flipkart" name="twitter:app:name:iphone"/><meta content="742044692" name="twitter:app:id:iphone"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:iphone"/><meta content="Flipkart" name="twitter:app:name:ipad"/><meta content="742044692" name="twitter:app:id:ipad"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:ipad"/><meta content="Flipkart" name="twitter:app:name:googleplay"/><meta content="com.flipkart.android" name="twitter:app:id:googleplay"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:googleplay"/><style>#container {
			height: 100%;
		}</style> <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/runtime.14f2c17a.js"></script><script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/vendor.79dfd802.js"></script><script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_common.3b9e09f1.js"></script><script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_modules.e2a4f33c.js"></script><script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app.de59d551.js"></script> <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/Browse.chunk.647087.css" rel="stylesheet"/><title>Smartphones- Buy Products Online at Best Price in India - All Categories | Flipkart.com</title><meta content="Smartphones- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="og_title" property="og:title"><meta content="Smartphones" name="Keywords"> <meta content="Smartphones- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" name="Description"><meta content="Smartphones- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" property="og:description"> <meta content="F4EEB3A0AFFDD385992A06E6920C0AC3" name="msvalidate.01"> <!--[if IE 9 ]>
	<script nonce="3945662651995770124">
		window.browserVersion = 'IE9';
		document.documentElement.className += ' ie9';
	</script>
	<![endif]--><!--[if !IE]><!--><script nonce="3945662651995770124">if (/*@cc_on!@*/false) {
			window.browserVersion = 'IE10';
			document.documentElement.className += ' ie10';
		}</script><!--<![endif]--> <script nonce="3945662651995770124">;window.NREUM||(NREUM={});NREUM.init={distributed_tracing:{enabled:true},privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]}};

			;NREUM.loader_config={accountID:"3700282",trustKey:"3679896",agentID:"1588759528",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528"}
			;NREUM.info={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528",sa:1}

			;/*! For license information please see nr-loader-spa-1.236.0.min.js.LICENSE.txt */

In [37]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <link href="https://rukminim2.flixcart.com" rel="preconnect"/>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.aa1465.css" rel="stylesheet"/>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.fbaef9.css" rel="stylesheet"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-type"/>
  <meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
  <meta content="102988293558" property="fb:page_id"/>
  <meta content="658873552,624500995,100000233612389" property="fb:admins"/>
  <link href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico" rel="shortcut icon"/>
  <link href="/osdd.xml?v=2" rel="search" type="application/opensearchdescription+xml"/>
  <meta content="website" property="og:type"/>
  <meta content="Flipkart.com" name="og_site_name" property="og:site_name"/>
  <link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
  <link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
  <link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
  <link href="/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
  <link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon"/>
  <meta content="app" name="twitter:card"/>
  <meta content="@flipkart" name="twitter:site"/>
  <meta content="@flipkart" name="twitter:creator"/>
  <meta content="Smartphones- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="twitter:title"/>
  <meta content="Shop for electronics, apparels &amp; more using our Flipkart app Free shipping &amp; COD." name="twitter:description"/>
  <meta content="in" name="twitter:app:country"/>
  <meta content="Flipkart" name="al:ios:app_name"/>
  <meta content="742044692" name="al:ios:app_store_id"/>
  <meta content="Flipkart" name="twitter:app:name:iphone"/>
  <meta content="742044692" name="twitter:app:id:iphone"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:iphone"/>
  <meta content="Flipkart" name="twitter:app:name:ipad"/>
  <meta content="742044692" name="twitter:app:id:ipad"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:ipad"/>
  <meta content="Flipkart" name="twitter:app:name:googleplay"/>
  <meta content="com.flipkart.android" name="twitter:app:id:googleplay"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:googleplay"/>
  <style>
   #container {
			height: 100%;
		}
  </style>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/runtime.14f2c17a.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/vendor.79dfd802.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_common.3b9e09f1.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_modules.e2a4f33c.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app.de59d551.js">
  </script>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/Browse.chunk.647087.css" rel="stylesheet"/>
  <title>
   Smartphones- Buy Products Online at Best Price in India - All Categories | Flipkart.com
  </title>
  <meta content="Smartphones- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="og_title" property="og:title">
   <meta content="Smartphones" name="Keywords">
    <meta content="Smartphones- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" name="Description">
     <meta content="Smartphones- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" property="og:description">
      <meta content="F4EEB3A0AFFDD385992A06E6920C0AC3" name="msvalidate.01">
       <!--[if IE 9 ]>
	<script nonce="3945662651995770124">
		window.browserVersion = 'IE9';
		document.documentElement.className += ' ie9';
	</script>
	<![endif]-->
       <!--[if !IE]><!-->
       <script nonce="3945662651995770124">
        if (/*@cc_on!@*/false) {
			window.browserVersion = 'IE10';
			document.documentElement.className += ' ie10';
		}
       </script>
       <!--<![endif]-->
       <script nonce="3945662651995770124">
        ;window.NREUM||(NREUM={});NREUM.init={distributed_tracing:{enabled:true},privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]}};

			;NREUM.loader_config={accountID:"3700282",trustKey:"3679896",agentID:"1588759528",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528"}
			;NREUM.info={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528",sa:1}

			;/*! For license information please see nr-loader-spa-1.236.0.min.js.LICENSE.txt */

In [38]:
soup.find('h1')